### ISSUE TITLE
Report Requirement

### ISSUE THREAD

**Issue by dichen001** [azhe825/CSC510#6]
Copied from Tim's answer from Piazza.

> See http://se16.unbox.org/project/feb1.md#what-to-hand-in
> 
> Find the template here: http://se16.unbox.org/project/report.md
> 
> The report should be part of your team's Github repository, and anyone of your teammates submits the link in the Feb1 column for your team on the URL submission spreadsheet by the deadline:
> https://docs.google.com/spreadsheets/d/1wxon-QXvDlDbkP95esby3HTEt2yZQezQRuxdCMm5lZg/edit#gid=0
> 
> Quote:
> Submit a 4+ page report using the report format describing
> Your evidence for P,U,T,G (defined below)
> 
> Your data collection methods - If participant observation, then write up your instruments - If literature review, define how you collected your data by answering these questions: - What were the review documents’s inclusion and exclusion criteria described and appropriate? - Is the literature search likely to have covered all relevant studies? - Did the reviewers assess the quality/validity of the included studies? (e.g. citations counts, recency) - Were the basic data/studies adequately described? (hint: see list of 5 above).
> 
> Your statement of the start up exercise (with some proposed sample output to show what you can do anything at all with these tools).

**Comment by amritbhanu** [comment]
Everyone please select 1 problem which either you have posted or by anyone of us. **Mention the topic here so that others can choose other ones**. And be ready with 1 page description on the whole of PUTGS by tomorrow. So, that we can start merging them. You are more than welcome to write on some extra problems if you want. As right now we have 5 problems and may be more coming our way.

**Comment by amritbhanu** [comment]
I am taking my problem of **Many of the user events are not captured properly when using an email system, which can provide good amount of information about those emails**

**Comment by azhe825** [comment]
Will take all the three topics of mine if no one else took from them

**Comment by jerry-shijieli** [comment]
I am focusing on the problem of **email feature extraction** process. Since nowadays, emails are not simply expressed in texts but instead involves lots of multi-media stuff(such as HTML and pictures) which are supported by the MIME format standards. Most research just throw away these infos which might be important for the accuracy of categorization. However, we won't use the multi-media directly, but instead convert some of these info into text format so that we can still apply those mature text mining methods to our project.
