### ISSUE TITLE
feedback, no grade (yet)

### ISSUE THREAD

**Issue by timm** [azhe825/CSC510#8]
&lt;facetious>
Hmmm...  I wonder wonder wonder where you got all those text mining ideas from?  
Can't really imagine...
&lt;/facetious> 

Project delivers on the required content.  And does so before the deadline: well done!

Please carry on along this path. I look forward to seeing the results of this project.

Technical comment:
- I wonder... what is the overlap of real mailboxes to the clusters found by automatic methods?
- Another clustering  tool is frequency of access. If two emails are touched in the same hour, should they be clustered?
- Please consider using LDA to find categorizations
- If you plan to use any user feedback to guide your clustering, then you may have a data collection timing problem- your miners might required 10000 to 100000s of examples to make useful conclusions. So if that is a risk, how could you best manage that risk?

**Comment by azhe825** [comment]
- We will NOT use unsupervised learning method since we want to provide users more flexibility. Users can create email folders with any arbitrary name they like. Classifier will be trained especially for this user with his or her folder set. Initially, dozens of emails will be required to put into each email folder as the training examples. The initial classifier can perform poorly due to the lack of training examples, therefore additional training examples will be collected while user is actually using this product (active learning and other method). 
- LDA can be considered, not as a clustering method but as a feature generation method.
- We are considering to have several models running simultaneously (maybe two), one is better with smaller training set, the other is better with larger training set. Set some rules to decide at a certain point of time, which model is used to make the final decision (or assign different confidence on the output of each model). This may be the last step of our project.

**Comment by amritbhanu** [comment]
- On the overlap, the automatic methods to find clusters/categories, doesn't give users much flexibility. They have to set specific rules in advanced section of mailboxes such as Gmail to do that.
